modLoader = "javafml"
loaderVersion = "[2,)"
#issueTrackerURL = ""
license = "All Rights Reserved"

[[mods]]
modId = "bettercombat"
version = "${version}"
displayName = "BetterCombat"
authors = "Daedelus"
credits="KosmX, Gecko"
description = '''
Easy, spectacular and fun melee combat system from Minecraft Dungeons.
'''
logoFile = "logo.png"

[[dependencies.bettercombat]]
modId = "neoforge"
type = "required"
versionRange = "[20.4,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.bettercombat]]
modId = "minecraft"
type = "required"
versionRange = "[1.20.4,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.bettercombat]]
modId="playeranimator"
type = "required"
versionRange="[1,)"
ordering="AFTER"
side="BOTH"

[[mixins]]
config = "bettercombat.mixins.json"
